name: Primeiro Workflow
on:
  push:
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Primeiro Workflow"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
